/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdLayoutRouteImport } from './routes/projects/$projectId/_layout'
import { Route as ProjectsProjectIdLayoutIndexRouteImport } from './routes/projects/$projectId/_layout.index'
import { Route as ProjectsProjectIdLayoutChatIdRouteImport } from './routes/projects/$projectId/_layout.$chatId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLayoutRoute = ProjectsProjectIdLayoutRouteImport.update({
  id: '/projects/$projectId/_layout',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLayoutIndexRoute =
  ProjectsProjectIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdLayoutRoute,
  } as any)
const ProjectsProjectIdLayoutChatIdRoute =
  ProjectsProjectIdLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => ProjectsProjectIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/$projectId': typeof ProjectsProjectIdLayoutRouteWithChildren
  '/projects/$projectId/$chatId': typeof ProjectsProjectIdLayoutChatIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/$projectId/$chatId': typeof ProjectsProjectIdLayoutChatIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/projects/$projectId/_layout': typeof ProjectsProjectIdLayoutRouteWithChildren
  '/projects/$projectId/_layout/$chatId': typeof ProjectsProjectIdLayoutChatIdRoute
  '/projects/$projectId/_layout/': typeof ProjectsProjectIdLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/projects/$projectId'
    | '/projects/$projectId/$chatId'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/projects/$projectId/$chatId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/projects/$projectId/_layout'
    | '/projects/$projectId/_layout/$chatId'
    | '/projects/$projectId/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProjectsProjectIdLayoutRoute: typeof ProjectsProjectIdLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/_layout': {
      id: '/projects/$projectId/_layout'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/_layout/': {
      id: '/projects/$projectId/_layout/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdLayoutIndexRouteImport
      parentRoute: typeof ProjectsProjectIdLayoutRoute
    }
    '/projects/$projectId/_layout/$chatId': {
      id: '/projects/$projectId/_layout/$chatId'
      path: '/$chatId'
      fullPath: '/projects/$projectId/$chatId'
      preLoaderRoute: typeof ProjectsProjectIdLayoutChatIdRouteImport
      parentRoute: typeof ProjectsProjectIdLayoutRoute
    }
  }
}

interface ProjectsProjectIdLayoutRouteChildren {
  ProjectsProjectIdLayoutChatIdRoute: typeof ProjectsProjectIdLayoutChatIdRoute
  ProjectsProjectIdLayoutIndexRoute: typeof ProjectsProjectIdLayoutIndexRoute
}

const ProjectsProjectIdLayoutRouteChildren: ProjectsProjectIdLayoutRouteChildren =
  {
    ProjectsProjectIdLayoutChatIdRoute: ProjectsProjectIdLayoutChatIdRoute,
    ProjectsProjectIdLayoutIndexRoute: ProjectsProjectIdLayoutIndexRoute,
  }

const ProjectsProjectIdLayoutRouteWithChildren =
  ProjectsProjectIdLayoutRoute._addFileChildren(
    ProjectsProjectIdLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProjectsProjectIdLayoutRoute: ProjectsProjectIdLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
